name: PlayerList
main: com.github.neapovil.playerlist.PlayerList
version: 1.0.0
api-version: 1.19
author: Neapovil
website: https://github.com/Neapovil/playerlist
depend:
  - CommandAPI
  - Core
softdepend:
  - PlaceholderAPI
  - Latency
  - Permissions
  - PermissionsYaml
permissions:
  playerlist.command:
    default: op
  playerlist.viewHiddenPlayers:
    default: op
