name: PlayerList
main: com.github.neapovil.playerlist.PlayerList
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/Neapovil/playerlist
depend:
  - CommandAPI
permissions:
  playerlist.command:
    default: op
